[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"

# Optional: make sure deploy previews build *all* branches
[context.deploy-preview]
  command = "bundle exec jekyll build"

[context.branch-deploy]
  command = "bundle exec jekyll build"